//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCCRUDWithEF.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Employee
    {
        [Display(Name = "ID")]
        public long Emp_Id { get; set; }

        [Display(Name = "Employee Name")]
        [Required]
        public string Name { get; set; }

        [Required]
        public string Position { get; set; }

        [Display(Name = "Office Location")]
        public string Office_Location { get; set; }

        [Required]
        public string Address { get; set; }

        [Required]
        public string Country { get; set; }

        [Required]
        public Nullable<decimal> Salary { get; set; }

        [Required]
        public Nullable<int> Age { get; set; }
    }
}
